OPENAI_API_KEY = "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"  # Thay bằng API key thật của bạn
